service: atomic_view
image: joelzwarrington/atomic_view

servers:
  web:
    hosts:
      - 5.78.123.56
    labels:
      traefik.http.routers.atomic_view.rule: Host(`atomic-view.joelw.dev`)
      traefik.http.routers.atomic_view_secure.entrypoints: websecure
      traefik.http.routers.atomic_view_secure.rule: Host(`atomic-view.joelw.dev`)
      traefik.http.routers.atomic_view_secure.tls: true
      traefik.http.routers.atomic_view_secure.tls.certresolver: letsencrypt

registry:
  username: joelzwarrington
  password:
    - KAMAL_REGISTRY_PASSWORD
  
env:
  secret:
    - RAILS_MASTER_KEY

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "joelw@hey.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web 
