# frozen_string_literal: true

pin_all_from File.expand_path("../app/assets/javascripts", __dir__)

# Also pinned under "controllers/atomic_view" (Stimulus' own subfolder
# namespacing rule: each "/" in a controller's path becomes "--" in its
# identifier) so a host app's own `eagerLoadControllersFrom("controllers",
# application)` -- boilerplate every Rails + importmap + Stimulus app
# already has, generated by stimulus-rails' install task -- discovers and
# registers these controllers automatically, no host app setup required.
# "controllers/atomic_view/toast_controller" -> "atomic-view--toast",
# matching every atomic_view component's `data-controller` attribute.
#
# `to:` is required here alongside `under:` -- without it, `under:` doubles
# as both the import name prefix *and* the on-disk asset path prefix (they
# only look decoupled below because `to:` makes them so), so importmap-rails
# would look for the files at "controllers/atomic_view/*.js" (which doesn't
# exist) instead of their real location, silently drop every one as an
# unresolvable asset, and this pin would do nothing.
#
# The plain "atomic_view/controllers/<name>_controller" alias from the pin
# above still works too, for a host app that wants to `import` and
# `application.register(...)` a controller by hand instead.
pin_all_from File.expand_path("../app/assets/javascripts/atomic_view/controllers", __dir__),
  under: "controllers/atomic_view", to: "atomic_view/controllers"

# `bin/importmap pin @floating-ui/dom` failed (the jspm.io generate API used
# by importmap-rails returned a 500), so this is pinned manually to
# jsDelivr's `+esm` bundle -- unlike jspm's `ga.jspm.io` build, jsDelivr's
# `+esm` output resolves its `@floating-ui/core`/`@floating-ui/utils`
# imports as same-origin absolute paths rather than bare specifiers, so it
# works as a single self-contained pin with no extra import map entries.
# Used by `dropdown_controller.js`.
pin "@floating-ui/dom", to: "https://cdn.jsdelivr.net/npm/@floating-ui/dom@1.8.0/+esm"

# `bin/importmap pin local-time` vendors the package locally under
# "vendor/javascript" -- which works for a real Rails app, but this engine's
# `atomic_view.precompile` initializer (see `engine.rb`) never adds
# "vendor/javascript" to `app.config.assets.paths`, so a host app can't
# actually serve the vendored file. Pinned to jsDelivr's `+esm` bundle
# instead, same fix as `@floating-ui/dom` above. Used by `ItemComponent`'s
# `local_time_ago` calls (see `TimelineComponent`'s class docs) -- the host
# app still needs to `import LocalTime from "local-time"; LocalTime.start()`
# per local_time's own Importmap install docs for times to localize
# client-side; without that the server-rendered UTC fallback text just
# stays as-is.
pin "local-time", to: "https://cdn.jsdelivr.net/npm/local-time@3.0.3/+esm"
