source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails", "~> 7.2.0"
gem "sprockets-rails"
gem "puma", ">= 5.0"

gem "tailwindcss-rails"
gem "lookbook"
gem "atomic_view", github: "joelzwarrington/atomic_view", branch: "main"
gem "view_component-form", github: "pantographe/view_component-form", branch: "main"

group :development do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "standardrb"
end
